# Generated by Django 5.0.7 on 2024-09-13 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('active', 'Activer'), ('paused', 'Suspendu'), ('completed', 'desactiver')], default='desactiver', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name="Nom du centre d'intérêt")),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom de la localisation')),
                ('country', models.CharField(max_length=100, verbose_name='Pays')),
                ('region', models.CharField(blank=True, max_length=100, null=True, verbose_name='Région')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ville')),
            ],
        ),
        migrations.CreateModel(
            name='Publicite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('mis_en_pause', 'Mis en pause'), ('termine', 'Terminé')], default='actif', max_length=12)),
                ('budget_quotidien', models.DecimalField(decimal_places=2, default='', max_digits=10)),
                ('ciblage', models.TextField(default='', help_text='Détails concernant les critères de ciblage.')),
                ('objectif_optimisation', models.CharField(choices=[('clics_lien', 'Clics sur le lien'), ('impressions', 'Impressions'), ('engagement', 'Engagement')], default='', max_length=20)),
                ('evenement_facturation', models.CharField(choices=[('impressions', 'Impressions'), ('clics', 'Clics')], default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Audience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name="Nom de l'audience")),
                ('description', models.TextField(blank=True, null=True, verbose_name="Description de l'audience")),
                ('age_min', models.PositiveIntegerField(default=18, verbose_name='Âge minimum')),
                ('age_max', models.PositiveIntegerField(default=65, verbose_name='Âge maximum')),
                ('gender', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin'), ('O', 'Autre')], max_length=1, verbose_name='Sexe')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('interests', models.ManyToManyField(related_name='audiences', to='services.interest', verbose_name="Centres d'intérêt")),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audiences', to='services.location', verbose_name='Localisation')),
            ],
        ),
    ]
