# Generated by Django 5.0.7 on 2024-09-03 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campagne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, null=True)),
                ('description', models.TextField()),
                ('public_cible', models.CharField(choices=[('adults', 'Adultes'), ('teenagers', 'Adolescents'), ('seniors', 'Seniors')], max_length=20, null=True)),
                ('objectifs', models.CharField(choices=[('conversions', 'Conversions'), ('trafic', 'Trafic'), ('engagement', 'Engagement'), ('vues_video', 'Vues vidéo')], max_length=50, null=True)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duree', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name="Nom du centre d'intérêt")),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom de la localisation')),
                ('country', models.CharField(max_length=100, verbose_name='Pays')),
                ('region', models.CharField(blank=True, max_length=100, null=True, verbose_name='Région')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ville')),
            ],
        ),
        migrations.CreateModel(
            name='Publicite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('type_contenu', models.CharField(choices=[('video', 'Vidéo'), ('image', 'Image'), ('texte', 'Texte')], max_length=20)),
                ('fichier', models.FileField(blank=True, null=True, upload_to='publicites/')),
            ],
        ),
        migrations.CreateModel(
            name='Audience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name="Nom de l'audience")),
                ('description', models.TextField(blank=True, null=True, verbose_name="Description de l'audience")),
                ('age_min', models.PositiveIntegerField(default=18, verbose_name='Âge minimum')),
                ('age_max', models.PositiveIntegerField(default=65, verbose_name='Âge maximum')),
                ('gender', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin'), ('O', 'Autre')], max_length=1, verbose_name='Sexe')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('interests', models.ManyToManyField(related_name='audiences', to='services.interest', verbose_name="Centres d'intérêt")),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audiences', to='services.location', verbose_name='Localisation')),
            ],
        ),
    ]
