# Generated by Django 5.0.7 on 2024-09-25 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicite',
            name='evenement_facturation',
            field=models.CharField(choices=[('impressions', 'Impressions'), ('clics', 'Clics')], max_length=20),
        ),
        migrations.AlterField(
            model_name='publicite',
            name='objectif_optimisation',
            field=models.CharField(choices=[('clics_lien', 'Clics sur le lien'), ('impressions', 'Impressions'), ('engagement', 'Engagement')], max_length=20),
        ),
    ]
