# Generated by Django 5.0.7 on 2024-09-26 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='facebookCampaign_ID',
            field=models.CharField(default='', max_length=200),
        ),
    ]
