# Generated by Django 5.0.7 on 2024-10-02 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='id_publication',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='post',
            new_name='id_publication',
        ),
    ]
