# Generated by Django 5.0.7 on 2024-09-26 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_campaign_facebookcampaign_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicite',
            name='campaign',
        ),
        migrations.AlterField(
            model_name='publicite',
            name='budget_quotidien',
            field=models.DecimalField(decimal_places=2, default='', max_digits=10),
        ),
        migrations.AlterField(
            model_name='publicite',
            name='evenement_facturation',
            field=models.CharField(choices=[('impressions', 'Impressions'), ('clics', 'Clics')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='publicite',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='publicite',
            name='objectif_optimisation',
            field=models.CharField(choices=[('clics_lien', 'Clics sur le lien'), ('impressions', 'Impressions'), ('engagement', 'Engagement')], default='', max_length=20),
        ),
    ]
