# Generated by Django 5.0.7 on 2024-09-25 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_publicite_evenement_facturation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicite',
            name='ciblage',
            field=models.CharField(max_length=255),
        ),
    ]
