# Generated by Django 5.0.7 on 2024-09-09 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_campaign_delete_campagne'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='status',
            field=models.CharField(choices=[('active', 'Activer'), ('paused', 'Suspendu'), ('completed', 'deactiver')], default='active', max_length=10),
        ),
    ]
