# Generated by Django 5.0.7 on 2024-10-02 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_rename_post_comment_id_publication_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='id_publication',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='id_publication',
            new_name='post',
        ),
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together={('comment_id', 'post')},
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('liker_id', 'post')},
        ),
    ]
