# Generated by Django 5.0.7 on 2024-09-10 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_campaign_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicite',
            name='description',
        ),
        migrations.RemoveField(
            model_name='publicite',
            name='fichier',
        ),
        migrations.RemoveField(
            model_name='publicite',
            name='titre',
        ),
        migrations.RemoveField(
            model_name='publicite',
            name='type_contenu',
        ),
        migrations.AddField(
            model_name='publicite',
            name='budget_quotidien',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=10),
        ),
        migrations.AddField(
            model_name='publicite',
            name='ciblage',
            field=models.TextField(default='null', help_text='Détails concernant les critères de ciblage.'),
        ),
        migrations.AddField(
            model_name='publicite',
            name='evenement_facturation',
            field=models.CharField(choices=[('impressions', 'Impressions'), ('clics', 'Clics')], default='null', max_length=20),
        ),
        migrations.AddField(
            model_name='publicite',
            name='nom',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AddField(
            model_name='publicite',
            name='objectif_optimisation',
            field=models.CharField(choices=[('clics_lien', 'Clics sur le lien'), ('impressions', 'Impressions'), ('engagement', 'Engagement')], default='null', max_length=20),
        ),
        migrations.AddField(
            model_name='publicite',
            name='statut',
            field=models.CharField(choices=[('actif', 'Actif'), ('mis_en_pause', 'Mis en pause'), ('termine', 'Terminé')], default='actif', max_length=12),
        ),
    ]
