# Generated by Django 5.0.7 on 2024-09-25 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_publicite_ciblage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicite',
            name='ciblage',
        ),
    ]
