# Generated by Django 5.0.7 on 2024-10-02 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_rename_id_publication_comment_post_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postpublication',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='postpublication',
            name='likes',
        ),
        migrations.AddField(
            model_name='postpublication',
            name='comment_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='postpublication',
            name='like_count',
            field=models.IntegerField(default=0),
        ),
    ]
