# Generated by Django 5.0.7 on 2024-10-02 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_remove_postpublication_comments_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postpublication',
            name='comment_count',
        ),
        migrations.RemoveField(
            model_name='postpublication',
            name='like_count',
        ),
        migrations.AddField(
            model_name='postpublication',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='post_comments', to='services.comment'),
        ),
        migrations.AddField(
            model_name='postpublication',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_posts', to='services.like'),
        ),
    ]
