# Generated by Django 5.0.7 on 2024-09-10 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_remove_publicite_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='status',
            field=models.CharField(choices=[('active', 'Activer'), ('paused', 'Suspendu'), ('completed', 'desactiver')], default='desactiver', max_length=10),
        ),
        migrations.AlterField(
            model_name='publicite',
            name='budget_quotidien',
            field=models.DecimalField(decimal_places=2, default='', max_digits=10),
        ),
        migrations.AlterField(
            model_name='publicite',
            name='ciblage',
            field=models.TextField(default='none', help_text='Détails concernant les critères de ciblage.'),
        ),
        migrations.AlterField(
            model_name='publicite',
            name='evenement_facturation',
            field=models.CharField(choices=[('impressions', 'Impressions'), ('clics', 'Clics')], default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='publicite',
            name='objectif_optimisation',
            field=models.CharField(choices=[('clics_lien', 'Clics sur le lien'), ('impressions', 'Impressions'), ('engagement', 'Engagement')], default='none', max_length=20),
        ),
    ]
