# Generated by Django 5.0.7 on 2024-10-02 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_remove_postpublication_comment_count_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postpublication',
            old_name='likes',
            new_name='post_likes',
        ),
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='postpublication',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='postpublication',
            name='image',
        ),
        migrations.RemoveField(
            model_name='postpublication',
            name='video',
        ),
        migrations.AddField(
            model_name='postpublication',
            name='comment_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='postpublication',
            name='like_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='postpublication',
            name='post_comments',
            field=models.ManyToManyField(blank=True, related_name='commented_posts', to='services.comment'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_id',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='services.postpublication'),
        ),
        migrations.AlterField(
            model_name='like',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='services.postpublication'),
        ),
        migrations.AlterField(
            model_name='postpublication',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='postpublication',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='postpublication',
            name='post_type',
            field=models.CharField(max_length=50),
        ),
    ]
