# Generated by Django 5.0.7 on 2024-10-02 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_rename_likes_postpublication_post_likes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postpublication',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='postpublication',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
