# Generated by Django 5.0.7 on 2024-10-02 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_postpublication_image_postpublication_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postpublication',
            name='post_comments',
            field=models.ManyToManyField(blank=True, related_name='commented_publications', to='services.comment'),
        ),
        migrations.AlterField(
            model_name='postpublication',
            name='post_likes',
            field=models.ManyToManyField(blank=True, related_name='liked_publications', to='services.like'),
        ),
    ]
