# Generated by Django 5.0.7 on 2024-10-04 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_commentreply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postpublication',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
