# Generated by Django 5.0.7 on 2024-10-09 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_alter_postpublication_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='postpublication',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='postpublication',
            name='post_type',
            field=models.CharField(choices=[('message', 'Message'), ('image', 'Image'), ('video', 'Vidéo'), ('link', 'Link')], max_length=50),
        ),
    ]
