# Generated by Django 5.0.7 on 2024-09-03 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='repeat_password',
        ),
    ]
