# Generated by Django 5.0.7 on 2024-08-22 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0002_user_delete_utilisateur'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
