# Generated by Django 5.0.7 on 2024-09-03 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0002_remove_utilisateur_repeat_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='confirm_password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
