# Generated by Django 5.0.7 on 2024-09-03 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0003_utilisateur_confirm_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='confirm_password',
        ),
    ]
