# Generated by Django 5.0.7 on 2024-08-26 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0004_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Campagne',
        ),
    ]
